version: '3.8'
services:
  app:
    build: .
    container_name: cinemas-app
    ports:
      - 8085:8085
    networks:
      - net-cinemas
    depends_on:
      - db-cinemas

  db:
    image: mongo
    container_name: db-cinemas
    ports:
      - 27017:27017
    volumes:
      - db-storage:/data/db
    networks:
      - net-cinemas

networks:
  net-cinemas:
volumes:
  db-storage: